[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
create_and_use_pda = "5Hsvd5MQfukMrBJY28Q2YouAfYRxM5ZyKPj3toQqsqS1"

[programs.devnet]
create_and_use_pda = "5Hsvd5MQfukMrBJY28Q2YouAfYRxM5ZyKPj3toQqsqS1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
